services:
  - type: web
    name: slack-bot-web
    env: python
    pythonVersion: 3.11
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python manage.py runserver 0.0.0.0:$PORT
    envVars:
      - key: SLACK_CLIENT_ID
        sync: false
      - key: SLACK_CLIENT_SECRET
        sync: false
      - key: SLACK_VERIFICATION_TOKEN
        sync: false
      - key: SLACK_BOT_USER_TOKEN
        sync: false